-- Brewway Production Baseline Migration
-- Generated from live Brewway Supabase database (project: xgvzsszzmlenkzyjtyyf)
-- This is the factual schema baseline for first customer production deployment.
-- Do NOT edit this file after generation. Hardening changes go in a separate migration.

-- =============================================================================
-- ENUM TYPES
-- =============================================================================

CREATE TYPE public.store_role AS ENUM ('owner', 'manager', 'staff');

CREATE TYPE public.order_status AS ENUM ('draft', 'pending_payment', 'paid', 'accepted', 'preparing', 'ready_for_pickup', 'completed', 'cancelled');

CREATE TYPE public.payment_status AS ENUM ('unpaid', 'pending', 'paid', 'rejected', 'refunded');

CREATE TYPE public.stock_movement_type AS ENUM ('in', 'out', 'adjustment', 'restore');

CREATE TYPE public.channel_fee_type AS ENUM ('none', 'percent', 'fixed');

-- =============================================================================
-- TABLES (in dependency order)
-- =============================================================================

CREATE TABLE public.stores (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    currency text NOT NULL DEFAULT 'THB',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    store_id uuid REFERENCES public.stores(id) ON DELETE SET NULL,
    email text NOT NULL,
    full_name text,
    role text NOT NULL DEFAULT 'staff' CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'staff'::text])),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.store_members (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    role public.store_role NOT NULL DEFAULT 'staff',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.product_categories (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    name text NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.products (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    category_id uuid REFERENCES public.product_categories(id) ON DELETE SET NULL,
    name text NOT NULL,
    description text,
    image_url text,
    base_price numeric NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    is_special boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    allow_sweetness boolean NOT NULL DEFAULT false,
    default_sweetness integer NOT NULL DEFAULT 0 CHECK (default_sweetness = ANY (ARRAY[0, 25, 50, 75, 100])),
    allow_extra_shot boolean NOT NULL DEFAULT false,
    extra_shot_price numeric NOT NULL DEFAULT 0 CHECK (extra_shot_price >= 0::numeric),
    max_extra_shots integer NOT NULL DEFAULT 0 CHECK (max_extra_shots >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.ingredients (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    name text NOT NULL,
    unit text NOT NULL,
    cost_per_unit numeric(12,4) NOT NULL DEFAULT 0,
    current_stock numeric(12,4) NOT NULL DEFAULT 0,
    low_stock_threshold numeric(12,4) NOT NULL DEFAULT 0,
    supplier_name text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    cost_type text NOT NULL DEFAULT 'ingredient' CHECK (cost_type = ANY (ARRAY['ingredient'::text, 'packaging'::text, 'consumable'::text, 'addon'::text, 'utility'::text, 'other'::text])),
    updated_at timestamptz NOT NULL DEFAULT now(),
    cost_source text NOT NULL DEFAULT 'manual' CHECK (cost_source = ANY (ARRAY['manual'::text, 'purchase_derived'::text, 'estimated'::text, 'migration'::text])),
    last_purchase_at timestamptz,
    cost_updated_at timestamptz
);

CREATE TABLE public.recipes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    ingredient_id uuid NOT NULL REFERENCES public.ingredients(id) ON DELETE RESTRICT,
    quantity_used numeric(12,4) NOT NULL DEFAULT 0,
    unit text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.product_addons (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id),
    product_id uuid NOT NULL REFERENCES public.products(id),
    name text NOT NULL,
    code text NOT NULL,
    addon_type text NOT NULL DEFAULT 'extra_shot',
    price numeric NOT NULL DEFAULT 0 CHECK (price >= 0::numeric),
    max_quantity integer NOT NULL DEFAULT 1 CHECK (max_quantity >= 0),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.product_addon_recipes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id),
    addon_id uuid NOT NULL REFERENCES public.product_addons(id),
    ingredient_id uuid NOT NULL REFERENCES public.ingredients(id),
    quantity_used numeric NOT NULL DEFAULT 0 CHECK (quantity_used >= 0::numeric),
    unit text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.sales_channels (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    name text NOT NULL,
    type text NOT NULL DEFAULT 'direct' CHECK (type = ANY (ARRAY['direct'::text, 'delivery'::text, 'manual'::text])),
    fee_type text NOT NULL DEFAULT 'none' CHECK (fee_type = ANY (ARRAY['none'::text, 'percent'::text, 'fixed'::text])),
    fee_value numeric(12,4) NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.channel_prices (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    channel_id uuid NOT NULL REFERENCES public.sales_channels(id) ON DELETE CASCADE,
    price numeric(12,2) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.customers (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    line_user_id text,
    display_name text,
    phone text,
    total_orders integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.orders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    order_no text NOT NULL,
    customer_id uuid REFERENCES public.customers(id) ON DELETE SET NULL,
    channel_id uuid REFERENCES public.sales_channels(id) ON DELETE SET NULL,
    order_type text NOT NULL DEFAULT 'manual' CHECK (order_type = ANY (ARRAY['pickup'::text, 'delivery'::text, 'manual'::text])),
    pickup_time timestamptz,
    status text NOT NULL DEFAULT 'draft' CHECK (status = ANY (ARRAY['draft'::text, 'pending_payment'::text, 'waiting_payment_review'::text, 'accepted'::text, 'preparing'::text, 'ready'::text, 'completed'::text, 'cancelled'::text, 'voided'::text])),
    payment_status text NOT NULL DEFAULT 'unpaid' CHECK (payment_status = ANY (ARRAY['unpaid'::text, 'pending_review'::text, 'paid'::text, 'rejected'::text, 'refunded'::text])),
    subtotal numeric NOT NULL DEFAULT 0,
    channel_fee numeric NOT NULL DEFAULT 0,
    total_amount numeric NOT NULL DEFAULT 0,
    total_cost numeric NOT NULL DEFAULT 0,
    gross_profit numeric NOT NULL DEFAULT 0,
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    channel text NOT NULL DEFAULT 'web_order',
    order_status text NOT NULL DEFAULT 'pending_payment' CHECK (order_status = ANY (ARRAY['draft'::text, 'pending_payment'::text, 'waiting_payment_review'::text, 'accepted'::text, 'preparing'::text, 'ready'::text, 'completed'::text, 'cancelled'::text, 'voided'::text])),
    pickup_type text NOT NULL DEFAULT 'pickup',
    discount_amount numeric NOT NULL DEFAULT 0,
    customer_note text,
    admin_note text,
    cancelled_reason text,
    cancelled_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    customer_name text,
    customer_phone text,
    order_source text NOT NULL DEFAULT 'web_order',
    public_token text
);

CREATE TABLE public.order_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id uuid REFERENCES public.products(id) ON DELETE SET NULL,
    quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price numeric(12,2) NOT NULL DEFAULT 0,
    unit_cost numeric(12,2) NOT NULL DEFAULT 0,
    total_price numeric(12,2) NOT NULL DEFAULT 0,
    total_cost numeric(12,2) NOT NULL DEFAULT 0,
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    product_name_snapshot text NOT NULL,
    line_profit numeric(12,2) NOT NULL DEFAULT 0,
    options jsonb NOT NULL DEFAULT '{}'::jsonb,
    option_total numeric(12,2) NOT NULL DEFAULT 0 CHECK (option_total >= 0::numeric),
    option_cost_total numeric(12,2) NOT NULL DEFAULT 0 CHECK (option_cost_total >= 0::numeric),
    CHECK (unit_price >= 0::numeric AND unit_cost >= 0::numeric AND total_price >= 0::numeric AND total_cost >= 0::numeric AND line_profit >= 0::numeric)
);

CREATE TABLE public.payments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    method text NOT NULL DEFAULT 'transfer' CHECK (method = ANY (ARRAY['transfer'::text, 'bank_transfer'::text, 'promptpay'::text, 'cash'::text, 'other'::text])),
    amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (amount >= 0::numeric),
    status text NOT NULL DEFAULT 'pending' CHECK (status = ANY (ARRAY['pending'::text, 'pending_review'::text, 'paid'::text, 'rejected'::text, 'refunded'::text])),
    slip_url text,
    confirmed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    confirmed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    customer_id uuid REFERENCES public.customers(id) ON DELETE SET NULL,
    slip_file_name text,
    slip_storage_path text,
    submitted_at timestamptz,
    reject_reason text,
    verified_by_api boolean NOT NULL DEFAULT false,
    verification_provider text,
    verification_status text,
    verification_score numeric(5,2),
    api_response jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.ingredient_purchases (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    ingredient_id uuid NOT NULL REFERENCES public.ingredients(id) ON DELETE RESTRICT,
    quantity numeric NOT NULL CHECK (quantity > 0::numeric),
    purchase_unit text NOT NULL,
    conversion_factor numeric NOT NULL DEFAULT 1 CHECK (conversion_factor > 0::numeric),
    normalized_quantity numeric NOT NULL CHECK (normalized_quantity > 0::numeric),
    base_unit_snapshot text,
    total_cost numeric NOT NULL CHECK (total_cost >= 0::numeric),
    unit_cost_snapshot numeric NOT NULL DEFAULT 0 CHECK (unit_cost_snapshot >= 0::numeric),
    supplier_name text,
    payment_status text NOT NULL DEFAULT 'paid' CHECK (payment_status = ANY (ARRAY['paid'::text, 'unpaid'::text, 'cancelled'::text])),
    paid_at timestamptz,
    due_date timestamptz,
    receipt_url text,
    receipt_storage_path text,
    note text,
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_perishable boolean NOT NULL DEFAULT false,
    lot_code text,
    expires_at timestamptz
);

CREATE TABLE public.stock_movements (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    ingredient_id uuid NOT NULL REFERENCES public.ingredients(id) ON DELETE CASCADE,
    movement_type text NOT NULL CHECK (movement_type = ANY (ARRAY['in'::text, 'used'::text, 'adjust'::text, 'return'::text])),
    quantity numeric NOT NULL,
    ref_order_id uuid REFERENCES public.orders(id) ON DELETE SET NULL,
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    purchase_id uuid REFERENCES public.ingredient_purchases(id) ON DELETE SET NULL,
    order_item_id uuid REFERENCES public.order_items(id) ON DELETE SET NULL,
    unit text,
    unit_cost_snapshot numeric CHECK (unit_cost_snapshot IS NULL OR unit_cost_snapshot >= 0::numeric),
    movement_reason text,
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE TABLE public.ingredient_waste_records (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id),
    ingredient_id uuid NOT NULL REFERENCES public.ingredients(id),
    purchase_id uuid REFERENCES public.ingredient_purchases(id),
    stock_movement_id uuid REFERENCES public.stock_movements(id),
    quantity numeric NOT NULL CHECK (quantity > 0::numeric),
    unit text NOT NULL,
    unit_cost_snapshot numeric NOT NULL DEFAULT 0 CHECK (unit_cost_snapshot >= 0::numeric),
    total_cost numeric NOT NULL DEFAULT 0 CHECK (total_cost >= 0::numeric),
    reason text NOT NULL CHECK (reason = ANY (ARRAY['expired'::text, 'damaged'::text, 'spill'::text, 'quality_issue'::text, 'manual_adjustment'::text, 'other'::text])),
    wasted_at timestamptz NOT NULL DEFAULT now(),
    note text,
    created_by uuid REFERENCES public.profiles(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (total_cost = round(quantity * unit_cost_snapshot, 4) OR total_cost >= 0::numeric)
);

CREATE TABLE public.order_status_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    from_status text,
    to_status text NOT NULL,
    changed_by uuid,
    changed_by_type text NOT NULL DEFAULT 'system' CHECK (changed_by_type = ANY (ARRAY['admin'::text, 'customer'::text, 'system'::text])),
    note text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.payment_status_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    payment_id uuid NOT NULL REFERENCES public.payments(id) ON DELETE CASCADE,
    order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    from_status text,
    to_status text NOT NULL,
    changed_by uuid,
    changed_by_type text NOT NULL DEFAULT 'system' CHECK (changed_by_type = ANY (ARRAY['admin'::text, 'customer'::text, 'system'::text])),
    note text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.overhead_expenses (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id),
    name text NOT NULL,
    category text NOT NULL DEFAULT 'other' CHECK (category = ANY (ARRAY['rent'::text, 'water'::text, 'electricity'::text, 'internet'::text, 'labor'::text, 'equipment'::text, 'transport'::text, 'marketing'::text, 'other'::text])),
    amount numeric NOT NULL DEFAULT 0 CHECK (amount >= 0::numeric),
    period text NOT NULL DEFAULT 'monthly' CHECK (period = ANY (ARRAY['daily'::text, 'weekly'::text, 'monthly'::text])),
    is_active boolean NOT NULL DEFAULT true,
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.planning_assumptions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id),
    expected_cups_per_month integer NOT NULL DEFAULT 300 CHECK (expected_cups_per_month > 0),
    operating_days_per_month integer NOT NULL DEFAULT 20 CHECK (operating_days_per_month > 0),
    target_profit_monthly numeric NOT NULL DEFAULT 0 CHECK (target_profit_monthly >= 0::numeric),
    overhead_allocation_method text NOT NULL DEFAULT 'per_cup' CHECK (overhead_allocation_method = ANY (ARRAY['per_cup'::text])),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.store_payment_settings (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    promptpay_qr_storage_path text,
    promptpay_qr_file_name text,
    promptpay_display_name text,
    is_promptpay_enabled boolean NOT NULL DEFAULT true,
    is_cash_enabled boolean NOT NULL DEFAULT true,
    updated_by uuid REFERENCES public.profiles(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (is_promptpay_enabled = true OR is_cash_enabled = true)
);

CREATE TABLE public.line_link_tokens (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
    customer_id uuid REFERENCES public.customers(id) ON DELETE SET NULL,
    line_user_id text NOT NULL,
    token_hash text NOT NULL,
    purpose text NOT NULL DEFAULT 'order_binding' CHECK (purpose = 'order_binding'::text),
    expires_at timestamptz NOT NULL CHECK (expires_at > created_at),
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.line_notification_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id uuid REFERENCES public.orders(id) ON DELETE SET NULL,
    customer_id uuid REFERENCES public.customers(id) ON DELETE SET NULL,
    line_user_id text NOT NULL,
    message_type text NOT NULL,
    message_payload jsonb,
    send_status text NOT NULL DEFAULT 'pending' CHECK (send_status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text])),
    error_message text,
    sent_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- =============================================================================
-- UNIQUE CONSTRAINTS
-- =============================================================================

ALTER TABLE public.store_members ADD CONSTRAINT store_members_store_id_user_id_key UNIQUE (store_id, user_id);
ALTER TABLE public.recipes ADD CONSTRAINT recipes_product_id_ingredient_id_key UNIQUE (product_id, ingredient_id);
ALTER TABLE public.channel_prices ADD CONSTRAINT channel_prices_product_id_channel_id_key UNIQUE (product_id, channel_id);
ALTER TABLE public.planning_assumptions ADD CONSTRAINT planning_assumptions_store_unique UNIQUE (store_id);
ALTER TABLE public.store_payment_settings ADD CONSTRAINT store_payment_settings_store_id_key UNIQUE (store_id);
ALTER TABLE public.line_link_tokens ADD CONSTRAINT line_link_tokens_token_hash_key UNIQUE (token_hash);
ALTER TABLE public.orders ADD CONSTRAINT orders_public_token_key UNIQUE (public_token);

-- =============================================================================
-- STANDALONE INDEXES (non-constraint)
-- =============================================================================

-- store_members (includes duplicate index store_members_store_user_unique — will be dropped in hardening migration)
CREATE UNIQUE INDEX store_members_store_user_unique ON public.store_members USING btree (store_id, user_id);

-- channel_prices
CREATE UNIQUE INDEX channel_prices_product_channel_unique ON public.channel_prices USING btree (store_id, product_id, channel_id);
CREATE INDEX idx_channel_prices_product_id ON public.channel_prices USING btree (product_id);
CREATE INDEX idx_channel_prices_store_id ON public.channel_prices USING btree (store_id);

-- customers
CREATE INDEX idx_customers_line_user_id ON public.customers USING btree (line_user_id);
CREATE INDEX idx_customers_store_id ON public.customers USING btree (store_id);
CREATE UNIQUE INDEX idx_customers_store_line_user_unique ON public.customers USING btree (store_id, line_user_id) WHERE (line_user_id IS NOT NULL);

-- ingredients
CREATE INDEX idx_ingredients_store_id ON public.ingredients USING btree (store_id);
CREATE INDEX idx_ingredients_store_cost_source ON public.ingredients USING btree (store_id, cost_source);
CREATE UNIQUE INDEX ingredients_store_name_unique ON public.ingredients USING btree (store_id, lower(TRIM(BOTH FROM name)));

-- ingredient_purchases
CREATE INDEX idx_ingredient_purchases_store_created_at ON public.ingredient_purchases USING btree (store_id, created_at DESC);
CREATE INDEX idx_ingredient_purchases_store_expiry ON public.ingredient_purchases USING btree (store_id, expires_at) WHERE (is_perishable = true);
CREATE INDEX idx_ingredient_purchases_store_ingredient ON public.ingredient_purchases USING btree (store_id, ingredient_id);
CREATE INDEX idx_ingredient_purchases_store_lot ON public.ingredient_purchases USING btree (store_id, lot_code) WHERE (lot_code IS NOT NULL);
CREATE INDEX idx_ingredient_purchases_store_payment_status ON public.ingredient_purchases USING btree (store_id, payment_status);
CREATE INDEX idx_ingredient_purchases_store_supplier ON public.ingredient_purchases USING btree (store_id, supplier_name);

-- ingredient_waste_records
CREATE INDEX idx_ingredient_waste_records_ingredient ON public.ingredient_waste_records USING btree (store_id, ingredient_id);
CREATE INDEX idx_ingredient_waste_records_purchase ON public.ingredient_waste_records USING btree (purchase_id) WHERE (purchase_id IS NOT NULL);
CREATE INDEX idx_ingredient_waste_records_reason ON public.ingredient_waste_records USING btree (store_id, reason, wasted_at DESC);
CREATE INDEX idx_ingredient_waste_records_store_date ON public.ingredient_waste_records USING btree (store_id, wasted_at DESC);

-- line_link_tokens
CREATE INDEX idx_line_link_tokens_customer_id ON public.line_link_tokens USING btree (customer_id);
CREATE INDEX idx_line_link_tokens_expires_at ON public.line_link_tokens USING btree (expires_at);
CREATE INDEX idx_line_link_tokens_store_line_user ON public.line_link_tokens USING btree (store_id, line_user_id);

-- line_notification_logs
CREATE INDEX idx_line_notification_logs_created_at ON public.line_notification_logs USING btree (created_at DESC);
CREATE INDEX idx_line_notification_logs_customer_id ON public.line_notification_logs USING btree (customer_id);
CREATE INDEX idx_line_notification_logs_line_user_created ON public.line_notification_logs USING btree (line_user_id, created_at DESC);
CREATE INDEX idx_line_notification_logs_line_user_id ON public.line_notification_logs USING btree (line_user_id);
CREATE INDEX idx_line_notification_logs_order_id ON public.line_notification_logs USING btree (order_id);
CREATE INDEX idx_line_notification_logs_send_status ON public.line_notification_logs USING btree (send_status);

-- order_items
CREATE INDEX idx_order_items_order_id ON public.order_items USING btree (order_id);
CREATE INDEX idx_order_items_product_id ON public.order_items USING btree (product_id);

-- order_status_logs
CREATE INDEX idx_order_status_logs_created_at ON public.order_status_logs USING btree (created_at DESC);
CREATE INDEX idx_order_status_logs_order_id ON public.order_status_logs USING btree (order_id);

-- orders
CREATE INDEX idx_orders_created_at ON public.orders USING btree (created_at);
CREATE INDEX idx_orders_pickup_time ON public.orders USING btree (pickup_time);
CREATE INDEX idx_orders_public_token ON public.orders USING btree (public_token);
CREATE INDEX idx_orders_store_id ON public.orders USING btree (store_id);
CREATE INDEX idx_orders_store_payment_status_created ON public.orders USING btree (store_id, payment_status, created_at DESC);
CREATE INDEX idx_orders_store_status_created ON public.orders USING btree (store_id, status, created_at DESC);
CREATE UNIQUE INDEX orders_store_order_no_unique ON public.orders USING btree (store_id, order_no);

-- overhead_expenses
CREATE INDEX idx_overhead_expenses_store_id ON public.overhead_expenses USING btree (store_id);
CREATE INDEX idx_overhead_expenses_store_active ON public.overhead_expenses USING btree (store_id, is_active);

-- payment_status_logs
CREATE INDEX idx_payment_status_logs_created_at ON public.payment_status_logs USING btree (created_at DESC);
CREATE INDEX idx_payment_status_logs_order_id ON public.payment_status_logs USING btree (order_id);
CREATE INDEX idx_payment_status_logs_payment_id ON public.payment_status_logs USING btree (payment_id);

-- payments
CREATE INDEX idx_payments_created_at ON public.payments USING btree (created_at DESC);
CREATE INDEX idx_payments_customer_id ON public.payments USING btree (customer_id);
CREATE INDEX idx_payments_order_id ON public.payments USING btree (order_id);
CREATE INDEX idx_payments_status ON public.payments USING btree (status);

-- planning_assumptions
CREATE INDEX idx_planning_assumptions_store_id ON public.planning_assumptions USING btree (store_id);

-- product_addon_recipes
CREATE UNIQUE INDEX product_addon_recipes_addon_ingredient_unique ON public.product_addon_recipes USING btree (store_id, addon_id, ingredient_id);

-- product_addons
CREATE UNIQUE INDEX product_addons_product_code_unique ON public.product_addons USING btree (store_id, product_id, code);

-- product_categories
CREATE INDEX idx_product_categories_store_id ON public.product_categories USING btree (store_id);

-- products
CREATE INDEX idx_products_store_id ON public.products USING btree (store_id);
CREATE UNIQUE INDEX products_store_name_unique ON public.products USING btree (store_id, lower(TRIM(BOTH FROM name)));

-- recipes
CREATE INDEX idx_recipes_product_id ON public.recipes USING btree (product_id);
CREATE INDEX idx_recipes_store_id ON public.recipes USING btree (store_id);
CREATE UNIQUE INDEX recipes_product_ingredient_unique ON public.recipes USING btree (store_id, product_id, ingredient_id);

-- sales_channels
CREATE INDEX idx_sales_channels_store_id ON public.sales_channels USING btree (store_id);
CREATE UNIQUE INDEX sales_channels_store_name_unique ON public.sales_channels USING btree (store_id, lower(TRIM(BOTH FROM name)));

-- stock_movements
CREATE INDEX idx_stock_movements_ingredient_id ON public.stock_movements USING btree (ingredient_id);
CREATE INDEX idx_stock_movements_order_item_id ON public.stock_movements USING btree (order_item_id);
CREATE INDEX idx_stock_movements_purchase_id ON public.stock_movements USING btree (purchase_id);
CREATE INDEX idx_stock_movements_store_id ON public.stock_movements USING btree (store_id);
CREATE INDEX idx_stock_movements_store_ingredient_created_at ON public.stock_movements USING btree (store_id, ingredient_id, created_at DESC);

-- store_payment_settings
CREATE INDEX idx_store_payment_settings_store_id ON public.store_payment_settings USING btree (store_id);
CREATE INDEX idx_store_payment_settings_updated_by ON public.store_payment_settings USING btree (updated_by);

-- =============================================================================
-- FUNCTIONS
-- =============================================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.valora_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.valora_set_ingredient_purchase_unit_cost()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.normalized_quantity IS NULL OR NEW.normalized_quantity <= 0 THEN
    NEW.normalized_quantity = NEW.quantity * COALESCE(NULLIF(NEW.conversion_factor, 0), 1);
  END IF;

  IF NEW.normalized_quantity <= 0 THEN
    RAISE EXCEPTION 'normalized_quantity must be greater than 0';
  END IF;

  NEW.unit_cost_snapshot = NEW.total_cost / NEW.normalized_quantity;
  NEW.updated_at = now();

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.calculate_order_item_totals()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
begin
  new.total_price = new.quantity * new.unit_price;
  new.total_cost = new.quantity * new.unit_cost;
  new.line_profit = new.total_price - new.total_cost;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.recalculate_order_totals(target_order_id uuid)
RETURNS void
LANGUAGE plpgsql
AS $function$
begin
  update public.orders
  set
    subtotal = coalesce((
      select sum(total_price)
      from public.order_items
      where order_id = target_order_id
    ), 0),

    total_cost = coalesce((
      select sum(total_cost)
      from public.order_items
      where order_id = target_order_id
    ), 0),

    total_amount = greatest(
      coalesce((
        select sum(total_price)
        from public.order_items
        where order_id = target_order_id
      ), 0) - discount_amount,
      0
    ),

    gross_profit =
      greatest(
        coalesce((
          select sum(total_price)
          from public.order_items
          where order_id = target_order_id
        ), 0) - discount_amount,
        0
      )
      - coalesce((
          select sum(total_cost)
          from public.order_items
          where order_id = target_order_id
        ), 0)
      - channel_fee,

    updated_at = now()
  where id = target_order_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.recalculate_order_after_item_change()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
begin
  if tg_op = 'DELETE' then
    perform public.recalculate_order_totals(old.order_id);
    return old;
  else
    perform public.recalculate_order_totals(new.order_id);
    return new;
  end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.sync_order_status_columns()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.order_status := NEW.status;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_order_status_legacy_status()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
begin
  if new.order_status is distinct from old.order_status then
    new.status = new.order_status;
  elsif new.status is distinct from old.status then
    new.order_status = new.status;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.sync_payment_to_order()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
begin
  if new.status = 'paid' then
    update public.orders
    set
      payment_status = 'paid',
      order_status = case
        when order_status in ('draft', 'pending_payment', 'waiting_payment_review') then 'accepted'
        else order_status
      end,
      status = case
        when status in ('draft', 'pending_payment', 'waiting_payment_review') then 'accepted'
        else status
      end,
      updated_at = now()
    where id = new.order_id;

  elsif new.status = 'rejected' then
    update public.orders
    set
      payment_status = 'rejected',
      order_status = 'pending_payment',
      status = 'pending_payment',
      updated_at = now()
    where id = new.order_id;

  elsif new.status in ('pending', 'pending_review') then
    update public.orders
    set
      payment_status = 'pending_review',
      order_status = 'waiting_payment_review',
      status = 'waiting_payment_review',
      updated_at = now()
    where id = new.order_id;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.log_order_status_change()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
begin
  if old.order_status is distinct from new.order_status then
    insert into public.order_status_logs (
      order_id,
      from_status,
      to_status,
      changed_by_type,
      note
    )
    values (
      new.id,
      old.order_status,
      new.order_status,
      'system',
      'Auto log from orders.order_status update'
    );
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.log_payment_status_change()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
begin
  if old.status is distinct from new.status then
    insert into public.payment_status_logs (
      payment_id,
      order_id,
      from_status,
      to_status,
      changed_by_type,
      note
    )
    values (
      new.id,
      new.order_id,
      old.status,
      new.status,
      'system',
      'Auto log from payments.status update'
    );
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.is_store_member(_store_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
AS $function$
  select exists (
    select 1 from public.store_members sm
    where sm.store_id = _store_id and sm.user_id = auth.uid()
  );
$function$;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
RETURNS event_trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
      RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

-- =============================================================================
-- TRIGGERS
-- =============================================================================

CREATE TRIGGER trg_channel_prices_updated_at BEFORE UPDATE ON public.channel_prices FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_customers_updated_at BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_ingredient_purchases_set_unit_cost BEFORE INSERT OR UPDATE ON public.ingredient_purchases FOR EACH ROW EXECUTE FUNCTION valora_set_ingredient_purchase_unit_cost();
CREATE TRIGGER trg_ingredient_purchases_updated_at BEFORE UPDATE ON public.ingredient_purchases FOR EACH ROW EXECUTE FUNCTION valora_set_updated_at();
CREATE TRIGGER trg_ingredients_updated_at BEFORE UPDATE ON public.ingredients FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_calculate_order_item_totals BEFORE INSERT OR UPDATE ON public.order_items FOR EACH ROW EXECUTE FUNCTION calculate_order_item_totals();
CREATE TRIGGER trg_recalculate_order_after_item_delete AFTER DELETE ON public.order_items FOR EACH ROW EXECUTE FUNCTION recalculate_order_after_item_change();
CREATE TRIGGER trg_recalculate_order_after_item_insert AFTER INSERT ON public.order_items FOR EACH ROW EXECUTE FUNCTION recalculate_order_after_item_change();
CREATE TRIGGER trg_recalculate_order_after_item_update AFTER UPDATE ON public.order_items FOR EACH ROW EXECUTE FUNCTION recalculate_order_after_item_change();
CREATE TRIGGER trg_log_order_status_change AFTER UPDATE OF order_status ON public.orders FOR EACH ROW EXECUTE FUNCTION log_order_status_change();
CREATE TRIGGER trg_orders_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sync_order_status_columns BEFORE INSERT OR UPDATE OF status ON public.orders FOR EACH ROW EXECUTE FUNCTION sync_order_status_columns();
CREATE TRIGGER trg_sync_order_status_legacy_status BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION sync_order_status_legacy_status();
CREATE TRIGGER trg_log_payment_status_change AFTER UPDATE OF status ON public.payments FOR EACH ROW EXECUTE FUNCTION log_payment_status_change();
CREATE TRIGGER trg_payments_updated_at BEFORE UPDATE ON public.payments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sync_payment_to_order AFTER INSERT OR UPDATE OF status ON public.payments FOR EACH ROW EXECUTE FUNCTION sync_payment_to_order();
CREATE TRIGGER trg_product_addon_recipes_updated_at BEFORE UPDATE ON public.product_addon_recipes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_product_addons_updated_at BEFORE UPDATE ON public.product_addons FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_product_categories_updated_at BEFORE UPDATE ON public.product_categories FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_recipes_updated_at BEFORE UPDATE ON public.recipes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sales_channels_updated_at BEFORE UPDATE ON public.sales_channels FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_store_payment_settings_updated_at BEFORE UPDATE ON public.store_payment_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================

ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_addon_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.channel_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingredient_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingredient_waste_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_status_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_status_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.overhead_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planning_assumptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_payment_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.line_link_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.line_notification_logs ENABLE ROW LEVEL SECURITY;

-- =============================================================================
-- RLS POLICIES
-- =============================================================================

-- channel_prices
CREATE POLICY "Public can read channel prices" ON public.channel_prices FOR SELECT TO anon, authenticated USING (true);

-- customers
CREATE POLICY "Public can insert customers" ON public.customers FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Store members can read customers" ON public.customers FOR SELECT TO authenticated USING (is_store_member(store_id));

-- ingredient_purchases
CREATE POLICY "ingredient_purchases_select_manager_only" ON public.ingredient_purchases FOR SELECT TO public USING (EXISTS (SELECT 1 FROM store_members sm WHERE sm.store_id = ingredient_purchases.store_id AND sm.user_id = auth.uid() AND sm.role::text = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text])));
CREATE POLICY "ingredient_purchases_insert_manager_only" ON public.ingredient_purchases FOR INSERT TO public WITH CHECK (EXISTS (SELECT 1 FROM store_members sm WHERE sm.store_id = ingredient_purchases.store_id AND sm.user_id = auth.uid() AND sm.role::text = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text])));
CREATE POLICY "ingredient_purchases_update_manager_only" ON public.ingredient_purchases FOR UPDATE TO public USING (EXISTS (SELECT 1 FROM store_members sm WHERE sm.store_id = ingredient_purchases.store_id AND sm.user_id = auth.uid() AND sm.role::text = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text]))) WITH CHECK (EXISTS (SELECT 1 FROM store_members sm WHERE sm.store_id = ingredient_purchases.store_id AND sm.user_id = auth.uid() AND sm.role::text = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text])));

-- order_items
CREATE POLICY "Public can insert order items" ON public.order_items FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Store members can read order items" ON public.order_items FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM orders o WHERE o.id = order_items.order_id AND is_store_member(o.store_id)));

-- order_status_logs
CREATE POLICY "Store members can insert order status logs" ON public.order_status_logs FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM orders o WHERE o.id = order_status_logs.order_id AND is_store_member(o.store_id)));

-- orders
CREATE POLICY "Public can insert orders" ON public.orders FOR INSERT TO anon, authenticated WITH CHECK (channel = ANY (ARRAY['web_order'::text, 'line_rich_menu'::text]) AND order_source = ANY (ARRAY['web_order'::text, 'line_rich_menu'::text]));
CREATE POLICY "Store members can read orders" ON public.orders FOR SELECT TO authenticated USING (is_store_member(store_id));
CREATE POLICY "Store members can update orders" ON public.orders FOR UPDATE TO authenticated USING (is_store_member(store_id)) WITH CHECK (is_store_member(store_id));

-- payment_status_logs
CREATE POLICY "Store members can insert payment status logs" ON public.payment_status_logs FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM orders o WHERE o.id = payment_status_logs.order_id AND is_store_member(o.store_id)));

-- payments
CREATE POLICY "Public can insert payments" ON public.payments FOR INSERT TO anon, authenticated WITH CHECK (status = ANY (ARRAY['pending'::text, 'pending_review'::text]));
CREATE POLICY "Store members can read payments" ON public.payments FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM orders o WHERE o.id = payments.order_id AND is_store_member(o.store_id)));
CREATE POLICY "Store members can update payments" ON public.payments FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM orders o WHERE o.id = payments.order_id AND is_store_member(o.store_id))) WITH CHECK (EXISTS (SELECT 1 FROM orders o WHERE o.id = payments.order_id AND is_store_member(o.store_id)));

-- product_categories
CREATE POLICY "Public can read product categories" ON public.product_categories FOR SELECT TO anon, authenticated USING (true);

-- products
CREATE POLICY "Public can read active products" ON public.products FOR SELECT TO anon, authenticated USING (is_active = true);

-- profiles
CREATE POLICY "Users can read own profile" ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid());

-- sales_channels
CREATE POLICY "Public can read active sales channels" ON public.sales_channels FOR SELECT TO anon, authenticated USING (is_active = true);

-- store_members
CREATE POLICY "store_members by store" ON public.store_members FOR ALL TO public USING (is_store_member(store_id)) WITH CHECK (is_store_member(store_id));

-- store_payment_settings
CREATE POLICY "store_payment_settings_select_store_members" ON public.store_payment_settings FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM store_members sm WHERE sm.store_id = store_payment_settings.store_id AND sm.user_id = auth.uid()));
CREATE POLICY "store_payment_settings_insert_managers" ON public.store_payment_settings FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM store_members sm WHERE sm.store_id = store_payment_settings.store_id AND sm.user_id = auth.uid() AND sm.role::text = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text])));
CREATE POLICY "store_payment_settings_update_managers" ON public.store_payment_settings FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM store_members sm WHERE sm.store_id = store_payment_settings.store_id AND sm.user_id = auth.uid() AND sm.role::text = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text]))) WITH CHECK (EXISTS (SELECT 1 FROM store_members sm WHERE sm.store_id = store_payment_settings.store_id AND sm.user_id = auth.uid() AND sm.role::text = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text])));
CREATE POLICY "store_payment_settings_delete_managers" ON public.store_payment_settings FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM store_members sm WHERE sm.store_id = store_payment_settings.store_id AND sm.user_id = auth.uid() AND sm.role::text = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text])));

-- =============================================================================
-- EVENT TRIGGER (auto-enable RLS on new tables)
-- =============================================================================

CREATE EVENT TRIGGER ensure_rls
ON ddl_command_end
EXECUTE FUNCTION public.rls_auto_enable();

-- =============================================================================
-- GRANTS (default Supabase pattern: all privileges to anon, authenticated, service_role)
-- =============================================================================

GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
